version: "3.8"
services:
  blog_app:
    container_name: blog_app
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - blog_db
    networks:
      - app_network

  blog_nginx:
    container_name: blog_nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - blog_app
    networks:
      - app_network

  blog_db:
    container_name: blog_db
    image: mysql:8.4
    restart: always
    volumes:
      - /my/own/datadir:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: driftwood
      MYSQL_ROOT_PASSWORD: Ridwan123@.
      MYSQL_USER: driftwood
      MYSQL_PASSWORD: Ridwan123@.
    networks:
      - app_network

  phpmyadmin:
    depends_on:
      - blog_db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: blog_db
      MYSQL_ROOT_PASSWORD: Ridwan123@.
    networks:
      - app_network

  blog_redis:
    container_name: blog_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge